#!/bin/sh

echo ====================================
echo iiMem::ref_ptr
iiMem/t.iiMem $*
echo 
echo ====================================

echo ====================================
echo std::tr1::shared_ptr
std/t.std $*
echo
echo ====================================

